# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReverseText = channel.unary_unary(
                '/Service/ReverseText',
                request_serializer=service__pb2.TextMessage.SerializeToString,
                response_deserializer=service__pb2.ReverseTextMessageResponse.FromString,
                )
        self.SplitText = channel.unary_unary(
                '/Service/SplitText',
                request_serializer=service__pb2.SplitTextRequest.SerializeToString,
                response_deserializer=service__pb2.SplitTextMessageResponse.FromString,
                )
        self.GetIsPrimeStream = channel.stream_stream(
                '/Service/GetIsPrimeStream',
                request_serializer=service__pb2.IntegerMessage.SerializeToString,
                response_deserializer=service__pb2.TextMessage.FromString,
                )


class ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReverseText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SplitText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIsPrimeStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReverseText': grpc.unary_unary_rpc_method_handler(
                    servicer.ReverseText,
                    request_deserializer=service__pb2.TextMessage.FromString,
                    response_serializer=service__pb2.ReverseTextMessageResponse.SerializeToString,
            ),
            'SplitText': grpc.unary_unary_rpc_method_handler(
                    servicer.SplitText,
                    request_deserializer=service__pb2.SplitTextRequest.FromString,
                    response_serializer=service__pb2.SplitTextMessageResponse.SerializeToString,
            ),
            'GetIsPrimeStream': grpc.stream_stream_rpc_method_handler(
                    servicer.GetIsPrimeStream,
                    request_deserializer=service__pb2.IntegerMessage.FromString,
                    response_serializer=service__pb2.TextMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReverseText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/ReverseText',
            service__pb2.TextMessage.SerializeToString,
            service__pb2.ReverseTextMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SplitText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Service/SplitText',
            service__pb2.SplitTextRequest.SerializeToString,
            service__pb2.SplitTextMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIsPrimeStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/Service/GetIsPrimeStream',
            service__pb2.IntegerMessage.SerializeToString,
            service__pb2.TextMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
