# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queue.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bqueue.proto\"\x1e\n\x0bTextMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"-\n\x08Response\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t2\x93\x01\n\x0fNewQueueService\x12\x1e\n\x03Put\x12\x0c.TextMessage\x1a\t.Response\x12\x1f\n\x04Peek\x12\x0c.TextMessage\x1a\t.Response\x12\x1e\n\x03Pop\x12\x0c.TextMessage\x1a\t.Response\x12\x1f\n\x04Size\x12\x0c.TextMessage\x1a\t.Responseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'queue_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEXTMESSAGE._serialized_start=15
  _TEXTMESSAGE._serialized_end=45
  _RESPONSE._serialized_start=47
  _RESPONSE._serialized_end=92
  _NEWQUEUESERVICE._serialized_start=95
  _NEWQUEUESERVICE._serialized_end=242
# @@protoc_insertion_point(module_scope)
